apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  labels:
    app: redis
    role: follower
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: follower
